export const SET_IMAGES = "SET_IMAGES"
export const SET_PAGE = "SET_PAGE"
export const SET_SECTION_IN_VIEW = "SET_SECTION_IN_VIEW"
export const SET_WINDOW = "SET_WINDOW"
export const SET_SORT = "SET_SORT_PARAMETERS"
export const SET_VIRAL_STATUS = "SET_VIRAL_STATUS"
export const SET_MODAL = "SET_MODAL"
export const SET_LOADING = "SET_LOADING"